---
name: CI + CD - Create Release 

on: 
  workflow_dispatch:
    inputs:
      TagName:
        description: 'Tag Name:'
        required: true 
        type: string              

      # selectedBranch:
      #   description: "Branch to use:"
      #   required: True
      #   default: "main"
      #   type: branch

jobs:

  create_release:
    runs-on: ubuntu-latest
    name: Create Release
    steps:
      
      - name: Checkout the repo
        uses: actions/checkout@dc323e67f16fb5f7663d20ff7941f27f5809e9b6
        with:
          fetch-depth: 0
          #ref: ${{ github.event.inputs.selectedBranch }}
        
      - name: Show environment
        run: env | grep ^GITHUB
      - name: Show ref v1
        run: echo "===============> Version from $GITHUB_REF"

      # - name: Extract release notes
      #   id: extract-release-notes       
      #   uses: ffurrer2/extract-release-notes@v1

      - name: Create new Github release tag
        id: create-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: PRE-${{github.event.inputs.TagName}}
          release_name: Release-${{github.event.inputs.TagName}}
          draft: false
          prerelease: true
          body_path: CHANGELOG.md

